### ISSUE TITLE
Hilfe benötigt

### ISSUE THREAD

**Issue by sebska** [gitmacer/Fritzfon-Solardisplay#1]
Hallo Tim,

ich versuche, das [Fritzfon-Smarthome-Solardisplay] bei mir zum laufen zu bekommen, ich scheitere aber. 
Ich bin neu in der Materie und Deine Anleitung erschließt sich mir nicht so.
Könntest Du mir bitte helfen?

Ich arbeite mit Solaranzeige.de auf einen RPI4. Die hat eine Influx-Datenbank. Die Daten stammen aus meiner Huawei Solaranlage (mit Batterie), über Grafana bekomme ich die Werte angezeigt. Bei Node-Red und dem Solar-2.1.4 schaffe ich es nicht.
Sonst auch gerne via Mail...

Gruss Sebastian

**Comment by gitmacer** [comment]
Versuche mal so einen Testaufbau: debug node auf Komplettes-Nachrichtenobjekt.
![grafik](https://github.com/gitmacer/Fritzfon-Smarthome-Solardisplay/assets/37345589/c46cacdf-2e51-43f9-a944-a838a9cad393)
![grafik](https://github.com/gitmacer/Fritzfon-Smarthome-Solardisplay/assets/37345589/da9f5ba0-2c0c-49c5-8bdd-26d9560e851e)
`SELECT last(*) FROM "PV"`
Was wird dann im Debug-Tab angezeigt?
Ich habe außerdem einen Discord server erstellt da ich denke, dass dies der beste/schnellste Weg fürshelfen ist.
https://discord.gg/BhDSDgXvtD

**Comment by gitmacer** [comment]
Solltest du (@sebska) es nun hinbekommen haben bitte ich dich dennoch um Rückmeldung, damit ich den Github Issue schließen kann und die Anleitung entsprechend verbessern kann. Danke.

**Comment by sebska** [comment]
Hallo Tim, ich schaffe es nicht, es so schnell zu testen. Ich verspreche aber, sofort nach dem Test zu schreiben. Es wird eventuell erst nächste Woche etwas. Viele Grüße Sebastian --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 15.09.23, 16:27 schrieb "Tim O. (macer)" ***@***.***>:

   
  Solltest du ***@***.***) es nun hinbekommen haben bitte ich dich dennoch um Rückmeldung, damit ich den Github Issue schließen kann und die Anleitung entsprechend verbessern kann. Danke.

**Comment by sebska** [comment]
Hallo Tim,Danke für den Schubs. Mit Deinem Vorschlag habe ich gesehen, was ich falsch mache. Ich habe die Datenbank mit falschem Namen angeredet.Eine Sache ist mir aufgefallen: im Smarthome.0.2.0 scheint noch ein Fehler mit den Einheiten zu sein. Er übernimmt die value22 Einheiten nicht aus der Maske, sondern value21 und value22 haben die Einheit von value21.Gruss Sebastian --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 14.09.23, 18:16 schrieb "Tim O. (macer)" ***@***.***>:

   
  Versuche mal so einen Testaufbau: debug node auf Komplettes-Nachrichtenobjekt.   SELECT last(*) FROM "PV" Was wird dann im Debug-Tab angezeigt? Ich habe außerdem einen Discord server erstellt da ich denke, dass dies der beste/schnellste Weg fürshelfen ist. https://discord.gg/BhDSDgXvtD

**Comment by gitmacer** [comment]
Ich habe soeben ein Update, welches diesen Fehler behebt und weitere Verbesserungen beinhaltet veröffentlicht.
Solltest du weitere Fehler finden oder jetzt alles funktioniert teile mir dies bitte mit.

Für die Doku würde ich noch gerne wissen, ob die Influxdb-Datenbank bei dem Solaranzeige projekt Passwort geschützt ist oder ob die Felder leerbleiben.

Solltest du zufrieden mit meinem Service und mein Projekt sein sodass du es weiterhin verwendest würde ich mich sehr über eine kleine donation und einem Stern auf Github freuen.

Dir noch einen schönen Tag.
Tim

**Comment by sebska** [comment]
Hallo Tim,mir ist noch etwas aufgefallen:ich wollte in der ersten Zeile "kein Icon" benutzen, dann werden aber auch nicht die Werte angezeigt (mit der 2.1.4-Version).Die Influx-Datenbank von Solaranzeige.de ist nicht passwortgeschützt. Gruss Sebastian --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 16.09.23, 15:52 schrieb "Tim O. (macer)" ***@***.***>:

   
  Ich habe soeben ein Update, welches diesen Fehler behebt und weitere Verbesserungen beinhaltet veröffentlicht. Solltest du weitere Fehler finden oder jetzt alles funktioniert teile mir dies bitte mit. 
  Für die Doku würde ich noch gerne wissen, ob die Influxdb-Datenbank bei dem Solaranzeige projekt Passwort geschützt ist oder ob die Felder leerbleiben. 
  Solltest du zufrieden mit meinem Service und mein Projekt sein sodass du es weiterhin verwendest würde ich mich sehr über eine kleine donation und einem Stern auf Github freuen. 
  Dir noch einen schönen Tag. Tim

**Comment by gitmacer** [comment]
Könntest du mir den Anwendungsfall schilder? Wenn du "Solar zu Haus" nicht brauchst kannst du seit der letzten Version der "Smarthome" version "Kein Icon" auswählen was genau das macht was du willst.
Bei der "Solar" version werden die Daten immer mit Namen angesprochen was mit "Kein Icon" nicht wirklich funktionieren würde und auch etwas größere Änderung benötigen würde. Allerdings wenn du die Funktion wirklich benötigst werde ich dies nochmal überdenken.

**Comment by gitmacer** [comment]
@sebska wie siehts aus? Ist die beschriebene Lösung zufriedenstellend? Gibt es sonst noch was bei dem du Hilfe benötigst?

**Comment by gitmacer** [comment]
@sebska Ich will dich nur kurz daran erinnern, dass ich auf eine Antwort warte. Sollte es sich erledigt haben bitte ich dennoch um Rückmeldung.

**Comment by sebska** [comment]
Hallo,ich hatte sehr viel um die Ohren, sorry für die späte Antwort. Die Lösung läuft, was ich noch nicht probiert habe (mangels Zeit): ein eigenes Icon Gruß --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 22.09.23, 17:40 schrieb "Tim O. (macer)" ***@***.***>:

   
  @sebska wie siehts aus? Ist die beschriebene Lösung zufriedenstellend? Gibt es sonst noch was bei dem du Hilfe benötigst?
